config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  devise_for :users

  resources :agencies, only: :show do
    resources :services, only: :index
    resources :employees, only: :index
  end

  resources :services, only: :show do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :create, :edit, :update, :delete]

  resources :employees, only: [:show, :edit]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agency.rb
class Agency < ApplicationRecord

has_many :employees
has_many :services

validates :brand, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :user

  validates :date, presence: true
  validates :user, presence: true
  validates :service, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :agency
  belongs_to :user

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :agency
  has_many :bookings

  validates :activity, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attachment :photo

  has_many :employees


  USER_TYPES = ["client", "employee", "manager"]
  validates :user_type, inclusion: {in: USER_TYPES}

  validates :first_name, presence: true
  validates :last_name, presence: true

  CAPACITIES = ["Full", "Level 1", "Level 2", "Level 3", "Under tutel"]
  validates :capacity, inclusion: {in: CAPACITIES}

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

  def show
    @agency = Agency.find(params[:id])
  end

  private

  def agency_params
    params.require(:agency).permit(:brand, :created_date, :owner, :director, :address, :phone, :contact_person, :mobile, :email, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type, :first_name, :last_name, :phone, :mobile, :st_number, :street, :zip, :city, :building, :code, :floor, :lift, :door, :comment, :capacity, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:user_type, :first_name, :last_name, :phone, :mobile, :st_number, :street, :zip, :city, :building, :code, :floor, :lift, :door, :comment, :capacity, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @service = Service.new
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.user = current_user
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render 'edit'
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @service = Service.find(params[:service_id])
    @booking.service = @service

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'services/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :date, :starting_time, :ending_time)
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  private

  def employee_params
    params.require(:employee).permit(:activity, :contract, :hired_date, :rib, :hourly_rate, :agency, :user)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
    @booking = Booking.new
  end

private

  def service_params
    params.require(:service).permit(:activity, :hourly_fee, :description, :agency, :picto)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_path_for(user)
    if user.photo.present?
      cl_image_path user.photo.path
    else
      image_path "avatar-inside-o-circle.png"
    end
  end
end

app/views/agencies/show.html.erb
<div class="container-agency">
  <div class="row">
    <div class="card-agency text-center">
      <div class="col-xs-12 col-sm-5">
        <div class="card-agency-brand">
          <h2> <%= @agency.brand %> </h2> <br>
          <p> Since <%= @agency.created_date %> </p>
        </div>
      </div>
      <div class="col-xs-2 col-offset-5 col-sm-2">
        <div class="card-agency-logo">
          <h3>logo</h3>
        </div>
      </div>
      <div class="col-xs-12 col-sm-5 col-offset-7">
        <div class="card-agency-contactdetails">
          <div class="card-agency-phone">
            <i class="fa fa-phone"></i> <%= @agency.phone %>
          </div>
          <div class="card-agency-address">
            <i class="fa fa-map-marker"></i> <%= @agency.address %>
          </div>
          <div class="card-agency-opening">
            <p><i class="fa fa-clock-o"></i> Monday-Friday : 8h-17h</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="card-agency-description">
            <div class="card-agency-description-title">
              <h4> <i class="fa fa-share-square"></i>  Description:</h4>
            </div>
            <br>
            <div class="card-agency-description-details">
              <p><%= @agency.description %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
         <div class="card-agency-map">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.2419022821477!2d2.3349305510717726!3d48.87266490755423!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e399f6ac9f7%3A0x1b7320b0f9631b55!2s14+Boulevard+Haussmann%2C+75009+Paris!5e0!3m2!1sfr!2sfr!4v1516703987935" width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>

         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="card-agency-admin">
            <div class="card-agency-admin-title">
              <h4><i class="fa fa-info-circle"></i> Agency admin details:</h4>
            </div>
            <br>
            <div class="card-agency-owner">
              <p>Owner:</p>
              <%= @agency.owner %>
            </div>
            <div class="card-agency-director">
              <p>Director:</p>
              <%= @agency.director %>
            </div>
            <div class="card-agency-contactperson">
              <p>Contact person:</p>
              <%= @agency.contact_person %>
            </div>
            <div class="card-agency-mobile">
              <p>Mobile:</p>
              <%= @agency.mobile %>
            </div>
            <div class="card-agency-email">
              <p>Email:</p>
              <%= @agency.email %>
            </div>
            <br>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <div class="message-box">
            <h4><i class="fa fa-envelope"></i>  Send a message to this agency!</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="bottom-links">
        <%= link_to 'Back', :back %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
     <title>Book this service !</title>
      <BR>
      <%= simple_form_for(@booking) do |f| %>


        <%= f.input :status, default: "reservation" %>
        <%= f.input :date, as: :string, input_html: { class: 'datepicker'} %>
        <%= f.input :starting_time, as: :text, input_html: { class: 'timepicker' } %>
        <%= f.input :ending_time, as: :text, input_html: { class: 'timepicker' } %>
      <BR>
        <%= f.button :submit %>
      <% end %>
      <BR>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
+<div class="container">
 +  <div class="row">
 +    <div class="col-xs-12 col-sm-6">
 +     <title>Book this service !</title>
 +      <BR>
 +      <%= simple_form_for(@booking) do |f| %>
 +        <%= f.input @booking.user %>
  +       <%= f.input @booking.service %>
          <%= f.input @booking.status default: "reservation" %>
          <%= f.input :date, as: :string, input_html: { class: 'datepicker'} %>
 +        <%= f.input :starting_time, as: :text, input_html: { class: 'timepicker' } %>
 +        <%= f.input :ending_time, as: :text, input_html: { class: 'timepicker' } %>
 +      <BR>
 +        <%= f.button :submit %>
 +      <% end %>
 +      <BR>
 +    </div>
 +  </div>
 +</div>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/index.html.erb
<div class="container-index-booking">

  <h3>Index Bookings </h3>

  <table id="table-index-booking">
    <thead>
      <tr>
        <th class="booking-created-at">MADE ON</th>
        <th class="booking-status">STATUS</th>
        <th class="booking-service">SERVICE</th>
        <th class="booking-date">DATE</th>
        <th class="booking-starting-time">FROM</th>
        <th class="booking-ending-time">TO</th>
        <th class="booking-user">CLIENT</th>
        <th class="booking-address">ADDRESS</th>
        <th class="booking-links">show|edit|delete</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr class="booking">
          <td><%= booking.created_at.strftime("%d/%m/%y  %H:%M") %></td>
          <td><%= booking.status %></td>
          <td><%= booking.service.activity %></td>
          <td><%= booking.date.strftime("%d/%m/%y") %></td>
          <td><%= booking.starting_time %></td>
          <td><%= booking.ending_time %></td>
          <td><%= booking.user.first_name %> <%= booking.user.last_name %></td>
          <td><%= booking.user.st_number %> <%= booking.user.street %>  <br> <%= booking.user.zip %> <%= booking.user.city %></td>
          <td><%= link_to 'show', booking_path(booking) %>
              <%= link_to 'edit', edit_booking_path(booking) %>
              <%= link_to 'delete', root_path %>

          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot></tfoot>
  </table>
</div>

app/views/bookings/show.html.erb
<div class="container-booking-show">
  <h3>Your booking details: </h3>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="wrapper-booking-show">
        <div class="booking-show">
          <div class="row">
            <div class="booking-show-status">
              <%= @booking.status %> <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 ">
              <i class="fa fa-calendar"></i>
              <%= @booking.date.strftime("%e/%m/%Y") %>
            </div>
            <div class="col-xs-6 ">
              <i class="fa fa-clock-o"></i>
              from : <%= @booking.starting_time %>
              to : <%= @booking.ending_time %>
            </div>
          </div>
          <div class="row">
            <div class="booking-show-service">
              <div class="booking-show-activity">
                <div class="card-service-activity">
                  <h3> <%= @booking.service.activity %> </h3>
                </div>
                <div class="card-service-picto">
                  <%= image_tag "#{@booking.service.activity.downcase}.png"  %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="booking-show-user">
              <i class="fa fa-user"></i>
              <%= @booking.user.first_name %> <%= @booking.user.last_name %> <hr>
            </div>
          </div>
          <div class="row">
            <div class="booking-show-address">
              <i class="fa fa-map-marker"></i>
              <%= @booking.user.st_number %>
              <%= @booking.user.street %> <br>
              <%= @booking.user.zip %>
              <%= @booking.user.city %> <hr>
            </div>
          </div>
          <div class="row">
            <div class="booking-show-price">
              <i class="fa fa-usd"></i>
              Price: <%= @booking.price %>. €
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-links">
    <%= link_to 'Back', :back %> |
    <%= link_to 'Bookings list', bookings_path %> |
    <%= link_to 'Services list', agency_services_path(:agency_id) %>
  </div>
</div>

app/views/employees/edit.html.erb
<h1>Employees#edit</h1>
<p>Find me in app/views/employees/edit.html.erb</p>

app/views/employees/index.html.erb
<div class="container-employees">
  <div class="row">
    <% @employees.each do |employee| %>
      <%= cl_image_tag image_path_for(employee.user), width: 50, height: 50, crop: :fill, class:"avatar" %>
      <%= employee.user.first_name %>
      <%= employee.user.last_name %>
      <%= employee.activity %>
      <%= employee.contract %>
      <%= employee.hired_date %>
      <%= employee.hourly_rate %>
      <%= employee.rib %>
      <br>
    <% end %>
  </div>
</div>

app/views/employees/show.html.erb
<div class="container-employees">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= cl_image_tag image_path_for(@employee.user), width: 100, height: 100, crop: :fill, class: "avatar" %>
      <%= @employee.user.first_name %>
      <%= @employee.user.last_name %>
      <%= @employee.activity %>
      <%= @employee.contract %>
      <%= @employee.hired_date %>
      <%= @employee.hourly_rate %>
      <%= @employee.rib %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta property="og:image" content="Anna">
    <meta property="og:description" content="concierge services">
    <meta propoerty="og:site_name" content="Anna">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'favicon.png' %>
    <title>Anna</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body class="<%= params[:controller] %> <%= params[:action] %>">
    <div class="main-body">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>

  </body>
</html>

app/views/pages/home.html.erb
<body>
  <div id="banner">
    <div class="banner-content">
      <h1>Anna</h1>
      <br>
      <p>Le service de conciergerie pour les agences de services à domicile et leur clients</p>
      <br>
      <button class="btn btn-primary" id="home-button">EN SAVOIR D'AVANTAGE</button>
    </div>
    <div class="banner-img" ></div>
  </div>

  <div class="container-home">
    <div class="container-title">
      <div class="title">
        <h1>LES EXPERTISES A VOTRE DISPOSITION</h1>
        <br>
        <p>Augmenter la rentabilité d’une agence de services aux séniors tout en améliorant significativement la satisfaction des clients et des salariés. <br>
        Une approche gagnant-gagnant pour tous.</p>
      </div>
    </div>
      <div class="wrapper-cards">
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <i class="fa fa-home fa-3x" aria hidden="true"></i>
              </div>
              <div class="card-title">
                <h3>Conciergerie Clients</h3>
              </div>
              <div class="card-text">
                <p>Compléter l’offre de services traditionnels : prestation de commande de billets sur internet, assistance administrative, …</p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <%= image_tag image_url("icon sliders.png") %>
              </div>
              <div class="card-title">
                <h3>Gestion de planning</h3>
              </div>
              <div class="card-text">
                <p>Automatisation des suivis de modifications, optimisation du taux d’activité, minimisation des temps morts entre les interventions, …</p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <i class="fa fa-address-book fa-3x" aria hidden="true"></i>
              </div>
              <div class="card-title">
                <h3>Dossiers Clients - CRM</h3>
              </div>
              <div class="card-text">
                <p>Centralisation des informations concernant le client, son domicile, ses habitudes, ses besoins, ses appréciations, ses opérations, …</p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <i class="fa fa-users fa-3x"></i>
              </div>
              <div class="card-title">
                <h3>Motivation des intervenants</h3>
              </div>
              <div class="card-text">
                <p>Techniques spécifiques pour augmenter la satisfaction employé, formations pour améliorer la satisfaction client, …</p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <%= image_tag image_url("icon circles.png") %>
              </div>
              <div class="card-title">
                <h3>Gestion 'paper-less'</h3>
              </div>
              <div class="card-text">
                <p>Limiter le papier : émission des bulletins de paie, dématérialisation des contrats, signature électronique, coffres forts digitaux, …</p>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card-icon">
                <i class="fa fa-plus fa-3x" aria hidden="true"></i>
              </div>
              <div class="card-title">
                <h3>Recrutement Clients & Intervenants</h3>
              </div>
              <div class="card-text">
                <p>Outils présentant des résultats concrets d’améliorations d’expériences clients et employés, outils de parrainage, …</p>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>

  <div class="container" id="pourquoi">
    <div class="container-content">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="home-picture">
            <%= image_tag image_url("starselect.jpeg") %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <div class="text">
            <h1>POURQUOI NOUS<br>SOMMES DIFFERENTS</h1>
            <br>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <br>
            <button class="btn btn-primary" id="home-button">EN SAVOIR D'AVANTAGE</button>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container" id="contactus">
    <div class="container-header text-center" >
      <h1>ENSEMBLE, DEVELOPPONS DE NOUVEAUX SERVICES</h1>
      <br>
      <h1 id="contactus-h1">CONTACTEZ NOUS</h1>
      <br>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="contact">
          <div class="contact-content">
            <h3>First name & Last name</h3><hr>
            <h3>Email address</h3><hr>
            <h3>City</h3><hr>
            <h3>Message</h3><hr>
            <br>
          </div>
          <div class="send-button">
            <button class="btn btn-primary" id="send-button">SEND</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/services/index.html.erb
<div class="container-index-service">  <div class="row">    <div class="text-center">      <h3>Easy booking form inline coming soon here !</h3>    </div>    <% @services.each do |service| %>    <div class="col-xs-12 col-sm-6 center">      <div class="wrapper-card-service">        <div class="card-service">          <div class="card-service-activity">            <h3> <%= service.activity %> </h3>          </div>          <div class="card-service-picto">            <%= image_tag "#{service.activity.downcase}.png" %>          </div>          <div class="card-service-link">            <%= link_to '', service_path(service), class: "card-service-link" %>          </div>        </div>      </div>    </div>    <% end %>  </div>  <div class="bottom-links">    <%= link_to 'Home', root_path %>  </div></div>

app/views/services/show.html.erb
<div class="container-service">
  <h3>Service selected:</h3>
  <div class="row">

    <div class="col-xs-12 col-sm-6">
      <div class="wrapper-card">
        <div class="card-service">
          <div class="card-service-activity">
            <h3> <%= @service.activity %> </h3>
          </div>
          <div class="card-service-picto">
            <%= image_tag "#{@service.activity.downcase}.png" %>
          </div>
        </div>
        <div class="card-service-details">
          <div class="card-service-agency">
            <div class="card-service-agency-text">
              <p>Operated by:</p>
            </div>
            <div class="card-service-agency-value">
              <%= link_to "#{@service.agency.brand}", agency_path(:"#{@service.agency.id}") %>
            </div>
          </div>
          <div class="card-service-price">
            <div class="card-service-price-text">
              <p>Hourly price:</p>
            </div>
            <div class="card-service-price-value">
              <%= @service.hourly_fee %>.- €
            </div>

          </div>
          <div class="card-service-description">
            <p>Description:</p>
            <p><%= @service.description %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="booking-form">
        <h3>Book this service !</h3>
        <%= simple_form_for([@service, @booking]) do |f| %>
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3">
            <%= f.input :date, as: :string, input_html: { class: 'datepicker' }%>
            <%= f.input :starting_time, as: :text, input_html: { class: 'timepicker' }%>
            <%= f.input :ending_time, as: :text, input_html: { class: 'timepicker' }%>
            <button class="btn btn-primary" id="booking-button">BOOK</button>
          </div>
        </div>

        <% end %>
      </div>
    </div>

    <div class="row">
    <div class="col-xs-12">
      <div class="bottom-links">
        <%= link_to 'Home', root_path %> | <%= link_to 'Index-Services', agency_services_path(:agency_id) %>
      </div>
    </div>
  </div>
 </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="text-center">
    <p>Follow us:</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-medium"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-anna.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Services", agency_services_path(:agency_id), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Calendar", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag image_path_for(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out)
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to new_user_session_path do %>
        <i class="fa fa-sign-in fa-2x"></i> <%= t('.sign_in', default: "") %>
      <% end %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>